# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 199089f16919ef3ed19ee45f437a4e505c7e8fb01565753255fc277d55ce3a520973402b9f8d297ff526d267f8d74ab86ecedae60e28367a94c154f4b0bbb42e

test:
  secret_key_base: 3beaf1066f8395a821a16def7ced7ca4b0993342b64179e3422b936b37c581b0a720fce7ae9c8926c97a43db2e58820ddd91b0500b610b59ad5d051a4c237e7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
